
name: teco_clock_v001
description: TECO Clock_V001 - UDP sender app (source project)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/teco_logo.png
